### ISSUE TITLE
Logarithmic volume?

### ISSUE THREAD

**Issue by stefandrissen** [stripwax/SAASound#11]
In his recently published book [Beep to Boom: The Development of Advanced Runtime Sound Systems for Games and Extended Reality](https://books.google.be/books?id=V8yGDwAAQBAJ), Simon N Goodwin writes:

> The volume controls of POKEY, TIA and SID supported 4-bit linear output in 15 even-sized steps. The AY, TI and SAA chips were superior in that respect because their volume controls used logarithmic 2 dB steps. Such non-linear volume controls are sensibly psychoacoustically weighted, so that each step up or down in volume sounded equivalent to the logarithmic human ear, but taking advantage of this requires that recordings made with a linear analogue-to-digital converter should be captured at much higher resolution and re-scaled as part of the conversion process.

I tried reading the source code - and failed - are SAASound's volumes logarithmic?

**Comment by stripwax** [comment]
Hm. The output of the code matched what I sampled from a real SAA, both from Sam original and, more recently, from a bare chip driven by a raspberry pi. It was entirely reverse engineered. I have no idea what the specs of the chip claim in this regard.I can double check, but I have no time at the moment unfortunately.
-------- Original message --------From: Stefan Drissen <notifications@github.com> Date: 03/05/2019  23:50  (GMT+00:00) To: stripwax/SAASound <SAASound@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [stripwax/SAASound] Logarithmic volume? (#11) In his recently published book Beep to Boom: The Development of Advanced Runtime Sound Systems for Games and Extended Reality", Simon N Goodwin writes:
"The volume controls of POKEY, TIA and SID supported 4-bit linear output in 15 even-sized steps. The AY, TI and SAA chips were superior in that respect because their volume controls used logarithmic 2 dB steps. Such non-linear volume controls are sensibly psychoacoustically weighted, so that each step up or down in volume sounded equivalent to the logarithmic human ear, but taking advantage of this requires that recordings made with a linear analogue-to-digital converter should be captured at much higher resolution and re-scaled as part of the conversion process."
I tried reading the source code - and failed - are SAASound's volumes logarithmic?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/stripwax/SAASound/issues/11",
"url": "https://github.com/stripwax/SAASound/issues/11",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by stripwax** [comment]
In fact, please also read this thread:https://www.vogons.org/viewtopic.php?f=9&t=51695&sid=732073f45e01400426e2899389a7d90f&start=60The bit density is linear wrt amplitude control. I don't see how that can be logarithmic.
-------- Original message --------From: Dave Hooper <dave@beermex.com> Date: 04/05/2019  11:35  (GMT+00:00) To: stripwax/SAASound <reply@reply.github.com>, stripwax/SAASound <SAASound@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [stripwax/SAASound] Logarithmic volume? (#11) Hm. The output of the code matched what I sampled from a real SAA, both from Sam original and, more recently, from a bare chip driven by a raspberry pi. It was entirely reverse engineered. I have no idea what the specs of the chip claim in this regard.I can double check, but I have no time at the moment unfortunately.

**Comment by stefandrissen** [comment]
Interesting reading - thanks. Simon better add an errata to his book ;-)
