### ISSUE TITLE
Feature request: record mixed + individual channels

### ISSUE THREAD

**Issue by stefandrissen** [stripwax/SAASound#9]
Hi Dave,

I wanted to put some SAM tunes into SidWiz 2 (https://appdb.winehq.org/objectManager.php?sClass=application&iId=18581).

The workflow with six channels is a bit boring. The same song needs to be started and recorded seven times (master + each channel separately).

It would be really cool if the audio recording option of SimCoupe could coax SAASound to output all seven versions at once! :-)

Cheers!

**Comment by stripwax** [comment]
Yep!  I'm looking to rearchitect SAASound a bit (hopefully not too extensively in one go though), so it's a great time to have feature requests  :)
Adding an API to provide output streams immediately prior to the final mix is definitely doable.

**Comment by stripwax** [comment]
So, I've had a think, and right now (given that the UI of simcoupe is not directly extensible from saasound), I reckon the easiest way to do this is for me to provide a kind of "saasound.cfg" file, where you could put in your preferred output file names, and saasound does the write directly into those files.  As raw pcm, since that's easier.  Would that work for you?
Also, pls try out the 3.3 release of SAASound when you can

**Comment by stefandrissen** [comment]
A config file would be fine.
Could a wav header be added to the raw pcm (https://stackoverflow.com/questions/28231198/how-to-add-playablesuch-as-wav-wmv-header-with-pcm-data-buffer-in-ios)?

I'll try 3.3 soon.

**Comment by stripwax** [comment]
That's easy enough too - but requires playback to be stopped, so I'll have to check whether SimCoupe shuts SAASound down cleanly or not (since wav header can only be written after total file length is known).
-------- Original message --------From: Stefan Drissen <notifications@github.com> Date: 05/07/2019  08:13  (GMT+00:00) To: stripwax/SAASound <SAASound@noreply.github.com> Cc: Dave Hooper <dave@beermex.com>, Comment <comment@noreply.github.com> Subject: Re: [stripwax/SAASound] Feature request: record mixed + individual
  channels (#9) A config file would be fine.
Could a wav header be added to the raw pcm (https://stackoverflow.com/questions/28231198/how-to-add-playablesuch-as-wav-wmv-header-with-pcm-data-buffer-in-ios)?
I'll try 3.3 soon.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/stripwax/SAASound/issues/9?email_source=notifications\u0026email_token=ABF47HBEO2ASCOBOTI5EQ43P53YAJA5CNFSM4GH5ZANKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZIXVHQ#issuecomment-508656286",
"url": "https://github.com/stripwax/SAASound/issues/9?email_source=notifications\u0026email_token=ABF47HBEO2ASCOBOTI5EQ43P53YAJA5CNFSM4GH5ZANKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZIXVHQ#issuecomment-508656286",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by stripwax** [comment]
My next task is to finish the plumbing around creating the saasound.cfg (nearly done).  I'll then be picking up this issue.

**Comment by stripwax** [comment]
@stefandrissen All done :-)

**Comment by stefandrissen** [comment]
Fantastic! Quick noob question here, what do I need to do to use the bleeding edge saasound.dll in SimCoupe? Just popping it and the cfg file in the SimCoupe folder results in:

---------------------------
SimCoupe.exe - Application Error
---------------------------
The application was unable to start correctly (0xc000007b). Click OK to close the application. 
---------------------------
OK   
---------------------------

**Comment by stripwax** [comment]
Hm that doesn't seem great! I've not yet tried the bleeding edge binaries built via the github automation yet, I naively assumed they would work the same as my local build. But yes it should be exactly as you described, plop the files into the simcoupe directory overwriting the existing saasound.dll . I'll take a look later!

**Comment by stripwax** [comment]
Which version of SimCoupe are you using?

**Comment by stefandrissen** [comment]
The latest - https://github.com/simonowen/simcoupe/releases/tag/20200827 - SimCoupe.exe dated 2020-08-28

**Comment by stripwax** [comment]
@stefandrissen ok.  I think I've squashed that problem.  The GitHub workflow seemed hard to convince into doing a x86 build instead of an x64 build by default, which is a problem I hadn't even contemplated, especially since my local toolchain defaulted to x86 build.  Anyway, after a few false starts, I've hacked the pipeline to invoke a different command for Windows builds, I've confirmed it's indeed now building for x86 not x64, and I've downloaded the release binary and confirmed it works (for me).  And I'm actually using an older SimCoupe build so you should be fine.
